"""
Deleted Files + Version History Report for S3 / Dell ECS
------------------------------------------------------

This script connects to an S3-compatible object storage system
(such as Dell EMC ECS), retrieves deleted objects and their version
history, and generates a timestamped Excel report.

Features:
- Uses configuration from constants.py
- Reports deleted files within the last 90 days
- Includes:
    * Path
    * Filename
    * Deleted date
    * Historical modification timestamps (if versioning enabled)
- Outputs Excel file to ./output folder
- Uses timestamped filenames for traceability

Requirements:
    pip install boto3 pandas openpyxl

Limitations:
- Historical modification data only exists if bucket versioning was enabled
- Cannot restore original LastModified timestamps directly

Author: Generated by Copilot
"""

import os
from datetime import datetime, timedelta, timezone

import boto3
import pandas as pd

# Import configuration values from constants.py
import constants


def ensure_output_directory(path):
    """
    Ensure the output directory exists.

    Args:
        path (str): Directory path to verify or create
    """
    if not os.path.exists(path):
        os.makedirs(path)


def create_s3_client():
    """
    Create and return an S3 client using ECS-compatible settings.

    Returns:
        boto3.client: Configured S3 client
    """
    return boto3.client(
        "s3",
        S3_ENDPOINT=constants.AWS_S3_ENDPOINT,
        ACCESS_KEY=constants.ACCESS_KEY,
        SECRET_KEY=constants.SECRET_KEY,
    )


def collect_deleted_file_data(s3_client, bucket, prefix, cutoff_date):
    """
    Collect deleted object data and version history.

    Args:
        s3_client: boto3 S3 client
        bucket (str): Bucket name
        prefix (str): Prefix (folder path)
        cutoff_date (datetime): Date filter (last 90 days)

    Returns:
        list: List of dictionaries representing report rows
    """
    records = []

    paginator = s3_client.get_paginator("list_object_versions")

    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):

        delete_markers = page.get("DeleteMarkers", [])
        versions = page.get("Versions", [])

        version_map = {}

        # Build version history per file
        for v in versions:
            key = v["Key"]
            last_modified = v["LastModified"]

            if last_modified >= cutoff_date:
                version_map.setdefault(key, []).append(last_modified)

        # Process deleted objects
        for d in delete_markers:
            key = d["Key"]
            deleted_date = d["LastModified"]

            if deleted_date < cutoff_date:
                continue

            path, filename = os.path.split(key)

            mod_dates = sorted(version_map.get(key, []))

            record = {
                "Path": path,
                "File": filename,
                "Deleted Date": deleted_date,
            }

            # Add modification history columns dynamically
            for i, dt in enumerate(mod_dates):
                record[f"Modified_{i+1}"] = dt

            records.append(record)

    return records


def export_to_excel(records, output_file):
    """
    Export collected records to Excel.

    Args:
        records (list): Report data
        output_file (str): Output Excel file path
    """
    if not records:
        print("No deleted files found in the specified time range.")
        return

    df = pd.DataFrame(records)
    
    base_cols = ["Path", "File", "Deleted Date"]
    other_cols = sorted([c for c in df.columns if c not in base_cols])
    
    df = df[base_cols + other_cols]
    
    # -------------------------------------------------------------------
    # OPTIONAL: Format datetime columns for cleaner Excel output
    # -------------------------------------------------------------------
    
    df["Deleted Date"] = pd.to_datetime(df["Deleted Date"]).dt.strftime("%Y-%m-%d %H:%M:%S")
    
    for col in df.columns:
        if col.startswith("Modified_"):
            df[col] = pd.to_datetime(df[col]).dt.strftime("%Y-%m-%d %H:%M:%S")
    
    # -------------------------------------------------------------------
    
    df.to_excel(output_file, index=False)

    print("Report created: " + output_file)


def main():
    """
    Main execution function.
    """
    bucket = constants.S3_BUCKET_NAME
    prefix = constants.S3_BUCKET_PREFIX

    cutoff_date = datetime.now(timezone.utc) - timedelta(days=90)

    output_dir = os.path.join(os.path.dirname(__file__), "output")
    ensure_output_directory(output_dir)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S")
    output_file = os.path.join(
        output_dir,
        f"Deleted_Files_Report_{timestamp}.xlsx",
    )

    s3_client = create_s3_client()

    records = collect_deleted_file_data(
        s3_client,
        bucket,
        prefix,
        cutoff_date,
    )

    export_to_excel(records, output_file)


if __name__ == "__main__":
    main()
