import os

OBJSTOR_ACCESS_KEY = os.environ["OBJSTOR_ACCESS_KEY"]
OBJSTOR_SECRET_KEY = os.environ["OBJSTOR_SECRET_KEY"]
OBJSTOR_BUCKET = os.environ["OBJSTOR_BUCKET"]
OBJSTOR_ENDPOINT = os.environ["OBJSTOR_ENDPOINT"]
