apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: objstor-pvc-data-sync-dev
spec:
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: datasync
              persistentVolumeClaim:
                claimName: wiof-dlvr-app-data-vol2
          backoffLimit: 6
          containers:
            - name: objstor-pvc-data-sync-dev
              image: image-registry.openshift-image-registry.svc:5000/b24326-dev/objstor-pvc-data-sync-dev:latest
              args:
              volumeMounts:
                - name: datasync
                  mountPath: /etc/datasync
              env:
                - name: OBJSTOR_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: objstor-datasync-dlvr
                      key: OBJSTOR_ACCESS_KEY
                - name: OBJSTOR_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: objstor-datasync-dlvr
                      key: OBJSTOR_BUCKET
                - name: OBJSTOR_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: objstor-datasync-dlvr
                      key: OBJSTOR_ENDPOINT
                - name: OBJSTOR_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: objstor-datasync-dlvr
                      key: OBJSTOR_SECRET_KEY
          restartPolicy: OnFailure
          failedJobsHistoryLimit: 3
          successfulJobsHistoryLimit: 3