apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sa-rbac
labels:
  app: ${app_name}
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${sa_name}
    namespace: ${license_plate}


- kind: Role
  apiVersion: authorization.openshift.io/v1
  metadata:
    name:  ${sa_role_name}
  rules:
    - resources:
        - configmaps
      verbs:
        - get
        - list
        - create
        - update
        - delete
        - patch
    - apiGroups:
        - apps.openshift.io
      resources:
        - deploymentconfigs
      verbs:
        - get
        - list
        - create
    - apiGroups:
        - route.openshift.io
      resources:
        - routes
      verbs:
        - get
        - list
        - create
        - patch
    - apiGroups:
        - networking.k8s.io
      resources:
        - networkpolicies
      verbs:
        - get
        - list
        - create
        - update
        - patch
        - delete

    - resources:
        - namespaces
        - projects
      verbs:
        - get
    - resources:
        - secrets
        - serviceaccounts
        - pods/exec
        - pods/portforward
        - pods
        - configmaps
        - replicationcontrollers
        - services
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
    - apiGroups:
        - networking.k8s.io
      resources:
        - ingresses
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
    - apiGroups:
        - rbac.authorization.k8s.io
      resources: 
        - rolebindings
        - roles
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - authorization.openshift.io
      resources: 
        - roles
        - rolebindings
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ${sa_role_binding_name}
    namespace: ${license_plate}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ${sa_role_name}
  subjects:
    - kind: ServiceAccount
      name: ${sa_name}
      namespace: ${license_plate}


parameters:
- name: app_name
  required: true
- name: license_plate
  required: true
- name: sa_role_name
  required: true
- name: sa_name
  required: true
- name: sa_role_binding_name
  required: true 